services:

  postgres:
    image: postgres:18-alpine
    container_name: fridge-app-postgres
    env_file:
      - .env-dev
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER:-fridge_dev}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - postgres

  # FastAPI application
  api:
    build:
      context: .
      dockerfile: ./src/fridge_app_backend/Dockerfile
    container_name: fridge-app-api
    env_file:
      - .env-dev
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - dev
    command: >
      uv run uvicorn fridge_app_backend.api.app:app --host 0.0.0.0 --port 8000  --root-path /backend
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: nickfedor/watchtower:arm64v8-dev
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.docker

  nginx:
    image: nginx:alpine
    container_name: fridge-app-nginx
    depends_on:
      - api
    ports:
      - "80:80"       # HTTP only for now
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  devcontainer:
    build:
      target: dev
    volumes:
      - ..:/workspaces
      - command-history-volume:/home/user/.history/
    profiles:
      - devcontainer

  app:
    build:
      target: app
    profiles:
      - app

volumes:
  command-history-volume:
  postgres_data:

